### ISSUE TITLE
Custom resource code is being compiled with lib

### ISSUE THREAD

**Issue by Butterneck** [schuettc/cdk-custom-resource-construct-example#15]
Hi,

building the lib compiles the code under `src/resources` as well. 
Thus the `package.json` and `yarn.lock` files are removed and the `NodeJsFunction` construct will fail because they're missing.

```
$ tree ./lib
lib
├── index.d.ts
├── index.js
├── resources
│   ├── index.d.ts
│   └── index.js
└── tsconfig.tsbuildinfo

1 directory, 5 files
```

The error when trying to use the construct (from python) is: 
```
raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Cannot find a package lock file (`pnpm-lock.yaml`, `yarn.lock` or `package-lock.json`). Please specify it with `depsLockFilePath`.
```

Do you have any hint on how to solve that?

**Comment by schuettc** [comment]
Yep.  Working on a replacement for that mode now.  It's a bit of an overhaul but hoping to have it out tonight.

**Comment by Butterneck** [comment]
Awesome! Thank you

**Comment by schuettc** [comment]
Updated with the projen Lambda Functions model.  It's a little different but solved a lot of problems for me.

https://projen.io/awscdk.html#aws-lambda-functions


It's a little weird looking but has been working well for me so far.

https://github.com/schuettc/cdk-custom-resource-construct-example/blob/672dede6c63c1e4fb2ea0a1c9f15fe65b4745e18/src/index.ts#L32-L40

**Comment by Butterneck** [comment]
Using projen Lambda Functions worked like a charm, thank you!

**Comment by schuettc** [comment]
Awesome!  Looks like the PR for upgrading projen to support NODEJS_18_X has been merged as well so that should work now.

https://github.com/projen/projen/pull/2289
